/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#47474e',
        'tertiary-dim': '#b0b5bd',
        'on-background': '#e7e4ec',
        'inverse-surface': '#fcf8fb',
        'surface-variant': '#25252b',
        'on-secondary-fixed-variant': '#5c5b5e',
        'on-tertiary-container': '#14171b',
        'on-surface': '#e7e4ec',
        'surface-dim': '#0e0e10',
        'primary-fixed': '#d6dbe2',
        'secondary-container': '#3b3b3e',
        'on-tertiary': '#101317',
        surface: '#0e0e10',
        'on-error-container': '#ff9993',
        'error-container': '#7f2927',
        'on-tertiary-fixed': '#000000',
        tertiary: '#ff8439',
        'surface-container-lowest': '#000000',
        outline: '#75757c',
        secondary: '#9f9da1',
        'surface-container-low': '#131316',
        'tertiary-container': '#8e959f',
        'primary-dim': '#aeb5bf',
        'on-error': '#490106',
        'surface-bright': '#2b2c32',
        'inverse-primary': '#2a313a',
        'on-primary': '#0f1216',
        'surface-container-highest': '#25252b',
        primary: '#c3c9d1',
        background: '#0e0e10',
        error: '#ee7d77',
        'on-secondary-fixed': '#3f3f42',
        'primary-fixed-dim': '#bcc3cc',
        'on-primary-fixed': '#171b20',
        'secondary-fixed': '#e4e1e5',
        'on-surface-variant': '#acaab1',
        'on-secondary-container': '#c1bec2',
        'on-tertiary-fixed-variant': '#421800',
        'on-secondary': '#202023',
        'tertiary-fixed-dim': '#e56500',
        'secondary-fixed-dim': '#d6d3d7',
        'primary-container': '#262c34',
        'inverse-on-surface': '#565457',
        'error-dim': '#bb5551',
        'surface-tint': '#c3c9d1',
        'surface-container': '#19191d',
        'on-primary-container': '#e2e6ec',
        'secondary-dim': '#9f9da1',
        'surface-container-high': '#1f1f24',
        'tertiary-fixed': '#9ba2ac',
        'on-primary-fixed-variant': '#2a313a',
      },
      fontFamily: {
        headline: ['Inter'],
        body: ['Inter'],
        label: ['Inter'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}

